//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Id { get; set; }
        public Nullable<int> FK_Member1 { get; set; }
        public Nullable<int> FK_Member2 { get; set; }
        public Nullable<int> FK_Member3 { get; set; }
        public Nullable<int> FK_Member4 { get; set; }
        public Nullable<int> FK_Member5 { get; set; }
        public Nullable<int> FK_Member6 { get; set; }
        public Nullable<int> FK_Member7 { get; set; }
        public Nullable<int> FK_Member8 { get; set; }
        public Nullable<int> FK_Member9 { get; set; }
        public Nullable<int> FK_Member10 { get; set; }
    }
}
