//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTask
    {
        public WorkTask()
        {
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public int Id { get; set; }
        public int FK_AssignedTo { get; set; }
        public int FK_Project { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> PercentageCompleted { get; set; }
        public Nullable<int> EstimatedDuration { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
