//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTeam.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyTeamDataEntities : DbContext
    {
        public MyTeamDataEntities()
            : base("name=MyTeamDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TeamMember> TeamMembers { get; set; }

        public System.Data.Entity.DbSet<MyTeam.Data.BEANS.EvaluationBEAN> EvaluationBEANs { get; set; }
    }
}
