//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTeam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Teams = new HashSet<Team>();
            this.Teams1 = new HashSet<Team>();
            this.Teams2 = new HashSet<Team>();
            this.Teams3 = new HashSet<Team>();
            this.Teams4 = new HashSet<Team>();
            this.Teams5 = new HashSet<Team>();
            this.Teams6 = new HashSet<Team>();
            this.Teams7 = new HashSet<Team>();
            this.Teams8 = new HashSet<Team>();
            this.Teams9 = new HashSet<Team>();
            this.WorkTasks = new HashSet<WorkTask>();
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public int PK_UserID { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime DOB { get; set; }
        public string SystemRole { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Team> Teams1 { get; set; }
        public virtual ICollection<Team> Teams2 { get; set; }
        public virtual ICollection<Team> Teams3 { get; set; }
        public virtual ICollection<Team> Teams4 { get; set; }
        public virtual ICollection<Team> Teams5 { get; set; }
        public virtual ICollection<Team> Teams6 { get; set; }
        public virtual ICollection<Team> Teams7 { get; set; }
        public virtual ICollection<Team> Teams8 { get; set; }
        public virtual ICollection<Team> Teams9 { get; set; }
        public virtual ICollection<WorkTask> WorkTasks { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
    }
}
